version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=db-startrack-dev
      - DB_PASSWORD=M4b6F/Z9U
      - DB_URL=jdbc:postgresql://localhost:5431/db-startrack-dev
      - DB_USER=startrackuserdev
      - DB_DRIVER=org.postgresql.Driver
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db-startrack-dev
      POSTGRES_USER: startrackusedev
      POSTGRES_PASSWORD: M4b6F/Z9U
    ports:
      - "5431:5431"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
    driver: local
